### ISSUE TITLE
Link Status does not update

### ISSUE THREAD

**Issue by rainerfritz** [RAKWireless/RAK13800-W5100S#1]
Hi !

The link status stays always on unknown, even when I have a cable connected and got an IP from my DHCP it still stays on unknown!
Probably something wrong in W5100Linkstatus W5100Class::getLinkStatus()
Would appreciate a fix, thx!
BR
Rainer

**Comment by beegee-tokyo** [comment]
Fix with https://github.com/RAKWireless/RAK13800-W5100S/commit/46685661a54d08f0101d5214ed27b01da425b5fb
